#!/bin/bash
set -e

# if the user inputted a positional arg, use that as the component dash name.
# otherwise, prompt.
if [ -n "$1" ]; then
  COMPONENTDASH="$1"
  echo "Cool, we're making a $COMPONENTDASH component."
else
  echo "Let's make a new component."
  printf "Enter the name of your component, in dash-case: "; read COMPONENTDASH
fi

COMPONENTUPPERCAMEL="$(echo "$COMPONENTDASH" | perl -pe 's/(^|-)./uc($&)/ge;s/_//g' | sed 's/-//g')"

first="$(echo $COMPONENTUPPERCAMEL | cut -c1 | tr [A-Z] [a-z])"
second="$(echo $COMPONENTUPPERCAMEL | cut -c2-)"
COMPONENTCAMEL="$first$second"

COMPONENTWORDS="$(echo "$COMPONENTDASH" | perl -pe 's/(^|-)./uc($&)/ge;s/_//g' | sed 's/-/ /g')"
COMPONENTUPPERSNAKE="$(echo "$COMPONENTDASH" | tr '-' '_' | tr a-z A-Z)"

echo "* Copying template to src/$COMPONENTDASH..."
cp -R src/.template src/$COMPONENTDASH

echo "* Replacing placeholders with variations of $COMPONENTDASH..."
for f in $(ls src/$COMPONENTDASH); do
  sed \
    -i .bkp \
    -e "s/%COMPONENTDASH%/$COMPONENTDASH/g" \
    -e "s/%COMPONENTCAMEL%/$COMPONENTCAMEL/g" \
    -e "s/%COMPONENTUPPERCAMEL%/$COMPONENTUPPERCAMEL/g" \
    -e "s/%COMPONENTWORDS%/$COMPONENTWORDS/g" \
    -e "s/%COMPONENTUPPERSNAKE%/$COMPONENTUPPERSNAKE/g" \
    src/$COMPONENTDASH/$f
  rm -f src/$COMPONENTDASH/$f.bkp
done

echo
echo "You have a new component in src/$COMPONENTDASH:"
echo
echo "* src/$COMPONENTDASH/index.js contains your component's code."
echo "* src/$COMPONENTDASH/story.js contains your component's story."
echo "* src/$COMPONENTDASH/styles.scss contains your component's styles."
echo

echo "* Press enter to open the documentation in your \$EDITOR, or Ctrl-C to skip that and get back
to it later."
read

EDITOR="${EDITOR:-vi}"
$EDITOR src/$COMPONENTDASH/README.md
